/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AccountProfile } from '../models';
/**
 * AccountInfoApi - axios parameter creator
 * @export
 */
export const AccountInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves profile/company info for an account.
         * @summary Retrieve account profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccountProfileUsingGET: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/account/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates profile/company info for an account.
         * @summary Updates an account profile
         * @param {AccountProfile} body accountInfo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccountInfoUsingPUT: async (body: AccountProfile, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateAccountInfoUsingPUT.');
            }
            const localVarPath = `/v1/account/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountInfoApi - functional programming interface
 * @export
 */
export const AccountInfoApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves profile/company info for an account.
         * @summary Retrieve account profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccountProfileUsingGET(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AccountProfile>>> {
            const localVarAxiosArgs = await AccountInfoApiAxiosParamCreator(configuration).getAccountProfileUsingGET(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Updates profile/company info for an account.
         * @summary Updates an account profile
         * @param {AccountProfile} body accountInfo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAccountInfoUsingPUT(body: AccountProfile, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AccountProfile>>> {
            const localVarAxiosArgs = await AccountInfoApiAxiosParamCreator(configuration).updateAccountInfoUsingPUT(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AccountInfoApi - factory interface
 * @export
 */
export const AccountInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Retrieves profile/company info for an account.
         * @summary Retrieve account profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccountProfileUsingGET(options?: AxiosRequestConfig): Promise<AxiosResponse<AccountProfile>> {
            return AccountInfoApiFp(configuration).getAccountProfileUsingGET(options).then((request) => request(axios, basePath));
        },
        /**
         * Updates profile/company info for an account.
         * @summary Updates an account profile
         * @param {AccountProfile} body accountInfo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAccountInfoUsingPUT(body: AccountProfile, options?: AxiosRequestConfig): Promise<AxiosResponse<AccountProfile>> {
            return AccountInfoApiFp(configuration).updateAccountInfoUsingPUT(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountInfoApi - object-oriented interface
 * @export
 * @class AccountInfoApi
 * @extends {BaseAPI}
 */
export class AccountInfoApi extends BaseAPI {
    /**
     * Retrieves profile/company info for an account.
     * @summary Retrieve account profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountInfoApi
     */
    public async getAccountProfileUsingGET(options?: AxiosRequestConfig) : Promise<AxiosResponse<AccountProfile>> {
        return AccountInfoApiFp(this.configuration).getAccountProfileUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Updates profile/company info for an account.
     * @summary Updates an account profile
     * @param {AccountProfile} body accountInfo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountInfoApi
     */
    public async updateAccountInfoUsingPUT(body: AccountProfile, options?: AxiosRequestConfig) : Promise<AxiosResponse<AccountProfile>> {
        return AccountInfoApiFp(this.configuration).updateAccountInfoUsingPUT(body, options).then((request) => request(this.axios, this.basePath));
    }
}
