/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContactAddress } from './contact-address';
 /**
 * Information about the company that owns/uses this account
 *
 * @export
 * @interface AccountProfile
 */
export interface AccountProfile {

    /**
     * @type {ContactAddress}
     * @memberof AccountProfile
     */
    address?: ContactAddress;

    /**
     * The goals of this business, ie. Grow Business, Convert more leads
     *
     * @type {Array<string>}
     * @memberof AccountProfile
     */
    businessGoals?: Array<string>;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    businessPrimaryColor?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    businessSecondaryColor?: string;

    /**
     * The type of business
     *
     * @type {string}
     * @memberof AccountProfile
     */
    businessType?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    currencyCode?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    email?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    languageTag?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    logoUrl?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    name?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    phone?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    phoneExt?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    timeZone?: string;

    /**
     * @type {string}
     * @memberof AccountProfile
     */
    website?: string;
}
