/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddressInformation
 */
export interface AddressInformation {

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    company?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    countryCode?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    firstName?: string;

    /**
     * @type {boolean}
     * @memberof AddressInformation
     */
    isInvoiceToCompany?: boolean;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    lastName?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    line1?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    line2?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    locality?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    middleName?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    phone?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    region?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    zipCode?: string;

    /**
     * @type {string}
     * @memberof AddressInformation
     */
    zipFour?: string;
}
