/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AffiliateRedirect
 */
export interface AffiliateRedirect {

    /**
     * @type {number}
     * @memberof AffiliateRedirect
     */
    affiliateId?: number;

    /**
     * @type {number}
     * @memberof AffiliateRedirect
     */
    id?: number;

    /**
     * @type {string}
     * @memberof AffiliateRedirect
     */
    localUrlCode?: string;

    /**
     * @type {string}
     * @memberof AffiliateRedirect
     */
    name?: string;

    /**
     * @type {Array<number>}
     * @memberof AffiliateRedirect
     */
    programIds?: Array<number>;

    /**
     * @type {string}
     * @memberof AffiliateRedirect
     */
    redirectUrl?: string;
}
