/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Appointment } from './appointment';
 /**
 * 
 *
 * @export
 * @interface AppointmentList
 */
export interface AppointmentList {

    /**
     * @type {Array<Appointment>}
     * @memberof AppointmentList
     */
    appointments?: Array<Appointment>;

    /**
     * @type {number}
     * @memberof AppointmentList
     */
    count?: number;

    /**
     * @type {string}
     * @memberof AppointmentList
     */
    next?: string;

    /**
     * @type {string}
     * @memberof AppointmentList
     */
    previous?: string;

    /**
     * @type {string}
     * @memberof AppointmentList
     */
    syncToken?: string;
}
