/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Goal } from './goal';
import { Sequence } from './sequence';
 /**
 * 
 *
 * @export
 * @interface Campaign
 */
export interface Campaign {

    /**
     * @type {number}
     * @memberof Campaign
     */
    createdByGlobalId?: number;

    /**
     * @type {Date}
     * @memberof Campaign
     */
    dateCreated?: Date;

    /**
     * @type {string}
     * @memberof Campaign
     */
    errorMessage?: string;

    /**
     * @type {Array<Goal>}
     * @memberof Campaign
     */
    goals?: Array<Goal>;

    /**
     * @type {number}
     * @memberof Campaign
     */
    id?: number;

    /**
     * @type {boolean}
     * @memberof Campaign
     */
    locked?: boolean;

    /**
     * @type {string}
     * @memberof Campaign
     */
    name?: string;

    /**
     * @type {Date}
     * @memberof Campaign
     */
    publishedDate?: Date;

    /**
     * @type {boolean}
     * @memberof Campaign
     */
    publishedStatus?: boolean;

    /**
     * @type {string}
     * @memberof Campaign
     */
    publishedTimeZone?: string;

    /**
     * @type {Array<Sequence>}
     * @memberof Campaign
     */
    sequences?: Array<Sequence>;

    /**
     * @type {string}
     * @memberof Campaign
     */
    timeZone?: string;
}
