/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CheckListItemDetails
 */
export interface CheckListItemDetails {

    /**
     * @type {string}
     * @memberof CheckListItemDetails
     */
    description?: string;

    /**
     * @type {Date}
     * @memberof CheckListItemDetails
     */
    doneDate?: Date;

    /**
     * @type {number}
     * @memberof CheckListItemDetails
     */
    id?: number;

    /**
     * @type {number}
     * @memberof CheckListItemDetails
     */
    instanceId?: number;

    /**
     * @type {number}
     * @memberof CheckListItemDetails
     */
    itemOrder?: number;

    /**
     * @type {boolean}
     * @memberof CheckListItemDetails
     */
    required?: boolean;
}
