/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ContactAddress
 */
export interface ContactAddress {

    /**
     * @type {string}
     * @memberof ContactAddress
     */
    countryCode?: string;

    /**
     * @type {string}
     * @memberof ContactAddress
     */
    field: ContactAddressFieldEnum;

    /**
     * @type {string}
     * @memberof ContactAddress
     */
    line1?: string;

    /**
     * @type {string}
     * @memberof ContactAddress
     */
    line2?: string;

    /**
     * @type {string}
     * @memberof ContactAddress
     */
    locality?: string;

    /**
     * Field used to store postal codes containing a combination of letters and numbers ex. 'EC1A', 'S1 2HE', '75000'
     *
     * @type {string}
     * @memberof ContactAddress
     */
    postalCode?: string;

    /**
     * @type {string}
     * @memberof ContactAddress
     */
    region?: string;

    /**
     * Mainly used in the United States, this is typically numeric. ex. '85001', '90002' Note: this is to be used instead of 'postal_code', not in addition to.
     *
     * @type {string}
     * @memberof ContactAddress
     */
    zipCode?: string;

    /**
     * Last four of a full zip code ex. '8244', '4320'. This field is supplemental to the zip_code field, otherwise will be ignored.
     *
     * @type {string}
     * @memberof ContactAddress
     */
    zipFour?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ContactAddressFieldEnum {
    BILLING = 'BILLING',
    SHIPPING = 'SHIPPING',
    OTHER = 'OTHER'
}

