/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateOrderItem
 */
export interface CreateOrderItem {

    /**
     * @type {string}
     * @memberof CreateOrderItem
     */
    description?: string;

    /**
     * Overridable price of the product, if not specified, the default will be used. Must be greater than or equal to 0.
     *
     * @type {string}
     * @memberof CreateOrderItem
     */
    price?: string;

    /**
     * The id of the product to be added to the order.
     *
     * @type {number}
     * @memberof CreateOrderItem
     */
    productId: number;

    /**
     * Quantity must be greater than or equal to 1
     *
     * @type {number}
     * @memberof CreateOrderItem
     */
    quantity: number;
}
