/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateProduct
 */
export interface CreateProduct {

    /**
     * @type {boolean}
     * @memberof CreateProduct
     */
    active?: boolean;

    /**
     * @type {string}
     * @memberof CreateProduct
     */
    productDesc?: string;

    /**
     * @type {string}
     * @memberof CreateProduct
     */
    productName: string;

    /**
     * @type {number}
     * @memberof CreateProduct
     */
    productPrice?: number;

    /**
     * @type {string}
     * @memberof CreateProduct
     */
    productShortDesc?: string;

    /**
     * @type {string}
     * @memberof CreateProduct
     */
    sku?: string;

    /**
     * @type {boolean}
     * @memberof CreateProduct
     */
    subscriptionOnly?: boolean;
}
