/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAffiliate
 */
export interface CreateAffiliate {

    /**
     * @type {string}
     * @memberof CreateAffiliate
     */
    code: string;

    /**
     * @type {number}
     * @memberof CreateAffiliate
     * @example 0
     */
    contactId: number;

    /**
     * @type {string}
     * @memberof CreateAffiliate
     */
    name?: string;

    /**
     * @type {boolean}
     * @memberof CreateAffiliate
     */
    notifyOnLead?: boolean;

    /**
     * @type {boolean}
     * @memberof CreateAffiliate
     */
    notifyOnSale?: boolean;

    /**
     * @type {number}
     * @memberof CreateAffiliate
     */
    parentId?: number;

    /**
     * @type {string}
     * @memberof CreateAffiliate
     */
    password: string;

    /**
     * @type {string}
     * @memberof CreateAffiliate
     */
    status?: CreateAffiliateStatusEnum;

    /**
     * @type {number}
     * @memberof CreateAffiliate
     */
    trackLeadsFor?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateAffiliateStatusEnum {
    Active = 'active',
    Inactive = 'inactive'
}

