/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateProductSubscription
 */
export interface CreateProductSubscription {

    /**
     * @type {boolean}
     * @memberof CreateProductSubscription
     */
    active?: boolean;

    /**
     * @type {string}
     * @memberof CreateProductSubscription
     */
    cycleType: CreateProductSubscriptionCycleTypeEnum;

    /**
     * @type {number}
     * @memberof CreateProductSubscription
     */
    frequency?: number;

    /**
     * @type {number}
     * @memberof CreateProductSubscription
     */
    numberOfCycles?: number;

    /**
     * @type {number}
     * @memberof CreateProductSubscription
     */
    planPrice: number;

    /**
     * @type {number}
     * @memberof CreateProductSubscription
     */
    subscriptionPlanIndex?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateProductSubscriptionCycleTypeEnum {
    YEAR = 'YEAR',
    MONTH = 'MONTH',
    WEEK = 'WEEK',
    DAY = 'DAY'
}

