/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CreateRestCustomFieldOption } from './create-rest-custom-field-option';
 /**
 * 
 *
 * @export
 * @interface CreateRestCustomField
 */
export interface CreateRestCustomField {

    /**
     * @type {string}
     * @memberof CreateRestCustomField
     */
    fieldType: CreateRestCustomFieldFieldTypeEnum;

    /**
     * An optional tab group to place the field under in the interface.  If not specified, will default to the 'Custom Fields' tab.
     *
     * @type {number}
     * @memberof CreateRestCustomField
     */
    groupId?: number;

    /**
     * @type {string}
     * @memberof CreateRestCustomField
     */
    label: string;

    /**
     * @type {Array<CreateRestCustomFieldOption>}
     * @memberof CreateRestCustomField
     */
    options?: Array<CreateRestCustomFieldOption>;

    /**
     * An optional user group to choose from when selecting values for User or UserListBox fields.
     *
     * @type {number}
     * @memberof CreateRestCustomField
     */
    userGroupId?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateRestCustomFieldFieldTypeEnum {
    Currency = 'Currency',
    Date = 'Date',
    DateTime = 'DateTime',
    DayOfWeek = 'DayOfWeek',
    Drilldown = 'Drilldown',
    Email = 'Email',
    Month = 'Month',
    ListBox = 'ListBox',
    Name = 'Name',
    WholeNumber = 'WholeNumber',
    DecimalNumber = 'DecimalNumber',
    Percent = 'Percent',
    PhoneNumber = 'PhoneNumber',
    Radio = 'Radio',
    Dropdown = 'Dropdown',
    SocialSecurityNumber = 'SocialSecurityNumber',
    State = 'State',
    Text = 'Text',
    TextArea = 'TextArea',
    User = 'User',
    UserListBox = 'UserListBox',
    Website = 'Website',
    Year = 'Year',
    YesNo = 'YesNo'
}

