/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AddressInformation } from './address-information';
import { CreateOrderItem } from './create-order-item';
 /**
 * 
 *
 * @export
 * @interface CreateOrder
 */
export interface CreateOrder {

    /**
     * @type {number}
     * @memberof CreateOrder
     */
    contactId: number;

    /**
     * @type {number}
     * @memberof CreateOrder
     */
    leadAffiliateId?: number;

    /**
     * @type {Date}
     * @memberof CreateOrder
     */
    orderDate: Date;

    /**
     * @type {Array<CreateOrderItem>}
     * @memberof CreateOrder
     */
    orderItems: Array<CreateOrderItem>;

    /**
     * @type {string}
     * @memberof CreateOrder
     */
    orderTitle: string;

    /**
     * @type {string}
     * @memberof CreateOrder
     */
    orderType: CreateOrderOrderTypeEnum;

    /**
     * Uses multiple strings as promo codes. The corresponding discount will be applied to the order.
     *
     * @type {Array<string>}
     * @memberof CreateOrder
     */
    promoCodes?: Array<string>;

    /**
     * @type {number}
     * @memberof CreateOrder
     */
    salesAffiliateId?: number;

    /**
     * @type {AddressInformation}
     * @memberof CreateOrder
     */
    shippingAddress?: AddressInformation;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateOrderOrderTypeEnum {
    Offline = 'Offline',
    Online = 'Online'
}

