/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomFieldOption } from './custom-field-option';
 /**
 * 
 *
 * @export
 * @interface CustomFieldMetaData
 */
export interface CustomFieldMetaData {

    /**
     * @type {string}
     * @memberof CustomFieldMetaData
     */
    defaultValue?: string;

    /**
     * @type {string}
     * @memberof CustomFieldMetaData
     */
    fieldName?: string;

    /**
     * @type {string}
     * @memberof CustomFieldMetaData
     */
    fieldType?: CustomFieldMetaDataFieldTypeEnum;

    /**
     * @type {number}
     * @memberof CustomFieldMetaData
     */
    id?: number;

    /**
     * @type {string}
     * @memberof CustomFieldMetaData
     */
    label?: string;

    /**
     * @type {Array<CustomFieldOption>}
     * @memberof CustomFieldMetaData
     */
    options?: Array<CustomFieldOption>;

    /**
     * @type {string}
     * @memberof CustomFieldMetaData
     */
    recordType?: CustomFieldMetaDataRecordTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CustomFieldMetaDataFieldTypeEnum {
    Currency = 'Currency',
    Date = 'Date',
    DateTime = 'DateTime',
    DayOfWeek = 'DayOfWeek',
    Drilldown = 'Drilldown',
    Email = 'Email',
    Month = 'Month',
    ListBox = 'ListBox',
    Name = 'Name',
    WholeNumber = 'WholeNumber',
    DecimalNumber = 'DecimalNumber',
    Percent = 'Percent',
    PhoneNumber = 'PhoneNumber',
    Radio = 'Radio',
    Dropdown = 'Dropdown',
    SocialSecurityNumber = 'SocialSecurityNumber',
    State = 'State',
    Text = 'Text',
    TextArea = 'TextArea',
    User = 'User',
    UserListBox = 'UserListBox',
    Website = 'Website',
    Year = 'Year',
    YesNo = 'YesNo'
}
/**
 * @export
 * @enum {string}
 */
export enum CustomFieldMetaDataRecordTypeEnum {
    CONTACT = 'CONTACT',
    REFERRALPARTNER = 'REFERRAL_PARTNER',
    OPPORTUNITY = 'OPPORTUNITY',
    TASKNOTEAPPOINTMENT = 'TASK_NOTE_APPOINTMENT',
    COMPANY = 'COMPANY',
    ORDER = 'ORDER',
    SUBSCRIPTION = 'SUBSCRIPTION'
}

