/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EcommerceReportingSimpleProduct
 */
export interface EcommerceReportingSimpleProduct {

    /**
     * @type {string}
     * @memberof EcommerceReportingSimpleProduct
     */
    description?: string;

    /**
     * @type {number}
     * @memberof EcommerceReportingSimpleProduct
     */
    id?: number;

    /**
     * @type {string}
     * @memberof EcommerceReportingSimpleProduct
     */
    name?: string;

    /**
     * @type {boolean}
     * @memberof EcommerceReportingSimpleProduct
     */
    shippable?: boolean;

    /**
     * @type {string}
     * @memberof EcommerceReportingSimpleProduct
     */
    sku?: string;

    /**
     * @type {boolean}
     * @memberof EcommerceReportingSimpleProduct
     */
    taxable?: boolean;
}
