/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EcommerceReportingOrderContactDetails } from './ecommerce-reporting-order-contact-details';
import { EcommerceReportingOrderItem } from './ecommerce-reporting-order-item';
import { EcommerceReportingPaymentPlan } from './ecommerce-reporting-payment-plan';
import { EcommerceReportingShippingInformation } from './ecommerce-reporting-shipping-information';
 /**
 * 
 *
 * @export
 * @interface EcommerceReportingOrder
 */
export interface EcommerceReportingOrder {

    /**
     * @type {boolean}
     * @memberof EcommerceReportingOrder
     */
    allowPayment?: boolean;

    /**
     * @type {boolean}
     * @memberof EcommerceReportingOrder
     */
    allowPaypal?: boolean;

    /**
     * @type {EcommerceReportingOrderContactDetails}
     * @memberof EcommerceReportingOrder
     */
    contact?: EcommerceReportingOrderContactDetails;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    creationDate?: string;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    id?: number;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    invoiceNumber?: number;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    leadAffiliateId?: number;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    modificationDate?: string;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    notes?: string;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    orderDate?: string;

    /**
     * @type {Array<EcommerceReportingOrderItem>}
     * @memberof EcommerceReportingOrder
     */
    orderItems?: Array<EcommerceReportingOrderItem>;

    /**
     * @type {EcommerceReportingPaymentPlan}
     * @memberof EcommerceReportingOrder
     */
    paymentPlan?: EcommerceReportingPaymentPlan;

    /**
     * @type {boolean}
     * @memberof EcommerceReportingOrder
     */
    recurring?: boolean;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    refundTotal?: number;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    salesAffiliateId?: number;

    /**
     * @type {EcommerceReportingShippingInformation}
     * @memberof EcommerceReportingOrder
     */
    shippingInformation?: EcommerceReportingShippingInformation;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    sourceType?: EcommerceReportingOrderSourceTypeEnum;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    status?: string;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    terms?: string;

    /**
     * @type {string}
     * @memberof EcommerceReportingOrder
     */
    title?: string;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    total?: number;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    totalDue?: number;

    /**
     * @type {number}
     * @memberof EcommerceReportingOrder
     */
    totalPaid?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum EcommerceReportingOrderSourceTypeEnum {
    INVOICE = 'INVOICE',
    API = 'API',
    CHECKOUTFORM = 'CHECKOUT_FORM',
    MANUALPAYMENT = 'MANUAL_PAYMENT',
    UNKNOWN = 'UNKNOWN',
    QBOSYNC = 'QBO_SYNC'
}

