/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EmailAddress
 */
export interface EmailAddress {

    /**
     * @type {string}
     * @memberof EmailAddress
     */
    email?: string;

    /**
     * @type {string}
     * @memberof EmailAddress
     */
    field: EmailAddressFieldEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum EmailAddressFieldEnum {
    EMAIL1 = 'EMAIL1',
    EMAIL2 = 'EMAIL2',
    EMAIL3 = 'EMAIL3'
}

