/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EmailSendRequestAttachment } from './email-send-request-attachment';
 /**
 * 
 *
 * @export
 * @interface EmailSendRequest
 */
export interface EmailSendRequest {

    /**
     * Email field of each Contact record to address the email to, such as 'Email', 'EmailAddress2', 'EmailAddress3' or '_CustomFieldName', defaulting to the contact's primary email
     *
     * @type {string}
     * @memberof EmailSendRequest
     */
    addressField?: string;

    /**
     * Attachments to be sent with each copy of the email, maximum of 10 with size of 1MB each
     *
     * @type {Array<EmailSendRequestAttachment>}
     * @memberof EmailSendRequest
     */
    attachments?: Array<EmailSendRequestAttachment>;

    /**
     * An array of Contact Ids to receive the email
     *
     * @type {Array<number>}
     * @memberof EmailSendRequest
     */
    contacts: Array<number>;

    /**
     * The HTML-formatted content of the email, encoded in Base64
     *
     * @type {string}
     * @memberof EmailSendRequest
     */
    htmlContent?: string;

    /**
     * The plain-text content of the email, encoded in Base64
     *
     * @type {string}
     * @memberof EmailSendRequest
     */
    plainContent?: string;

    /**
     * The subject line of the email
     *
     * @type {string}
     * @memberof EmailSendRequest
     */
    subject: string;

    /**
     * The infusionsoft user to send the email on behalf of
     *
     * @type {number}
     * @memberof EmailSendRequest
     */
    userId: number;
}
