/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FaxNumber
 */
export interface FaxNumber {

    /**
     * @type {string}
     * @memberof FaxNumber
     */
    field: FaxNumberFieldEnum;

    /**
     * @type {string}
     * @memberof FaxNumber
     */
    number?: string;

    /**
     * @type {string}
     * @memberof FaxNumber
     */
    type?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum FaxNumberFieldEnum {
    FAX1 = 'FAX1',
    FAX2 = 'FAX2'
}

