/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface FileUpload
 */
export interface FileUpload {

    /**
     * @type {string}
     * @memberof FileUpload
     */
    fileName: string;

    /**
     * @type {boolean}
     * @memberof FileUpload
     */
    _public?: boolean;

    /**
     * @type {string}
     * @memberof FileUpload
     */
    fileData: string;

    /**
     * @type {number}
     * @memberof FileUpload
     */
    contactId?: number;

    /**
     * @type {boolean}
     * @memberof FileUpload
     */
    isPublic: boolean;

    /**
     * @type {string}
     * @memberof FileUpload
     */
    fileAssociation: FileUploadFileAssociationEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum FileUploadFileAssociationEnum {
    CONTACT = 'CONTACT',
    USER = 'USER',
    COMPANY = 'COMPANY'
}

