/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CompanyReference } from './company-reference';
import { ContactAddress } from './contact-address';
import { ContactOrigin } from './contact-origin';
import { CustomFieldValue } from './custom-field-value';
import { EmailAddress } from './email-address';
import { FaxNumber } from './fax-number';
import { PhoneNumber } from './phone-number';
import { Relationship } from './relationship';
import { SocialAccount } from './social-account';
 /**
 * 
 *
 * @export
 * @interface FullContact
 */
export interface FullContact {

    /**
     * @type {string}
     * @memberof FullContact
     */
    scoreValue?: string;

    /**
     * @type {Array<ContactAddress>}
     * @memberof FullContact
     */
    addresses?: Array<ContactAddress>;

    /**
     * @type {Date}
     * @memberof FullContact
     */
    anniversary?: Date;

    /**
     * @type {Date}
     * @memberof FullContact
     */
    birthday?: Date;

    /**
     * @type {CompanyReference}
     * @memberof FullContact
     */
    company?: CompanyReference;

    /**
     * @type {string}
     * @memberof FullContact
     */
    companyName?: string;

    /**
     * @type {string}
     * @memberof FullContact
     */
    contactType?: string;

    /**
     * @type {Array<CustomFieldValue>}
     * @memberof FullContact
     */
    customFields?: Array<CustomFieldValue>;

    /**
     * @type {Date}
     * @memberof FullContact
     */
    dateCreated?: Date;

    /**
     * @type {Array<EmailAddress>}
     * @memberof FullContact
     */
    emailAddresses?: Array<EmailAddress>;

    /**
     * @type {boolean}
     * @memberof FullContact
     */
    emailOptedIn?: boolean;

    /**
     * @type {string}
     * @memberof FullContact
     */
    emailStatus?: FullContactEmailStatusEnum;

    /**
     * @type {string}
     * @memberof FullContact
     */
    familyName?: string;

    /**
     * @type {Array<FaxNumber>}
     * @memberof FullContact
     */
    faxNumbers?: Array<FaxNumber>;

    /**
     * @type {string}
     * @memberof FullContact
     */
    givenName?: string;

    /**
     * @type {number}
     * @memberof FullContact
     */
    id?: number;

    /**
     * @type {string}
     * @memberof FullContact
     */
    jobTitle?: string;

    /**
     * @type {Date}
     * @memberof FullContact
     */
    lastUpdated?: Date;

    /**
     * @type {number}
     * @memberof FullContact
     */
    leadSourceId?: number;

    /**
     * @type {string}
     * @memberof FullContact
     */
    middleName?: string;

    /**
     * @type {string}
     * @memberof FullContact
     */
    optInReason?: string;

    /**
     * @type {ContactOrigin}
     * @memberof FullContact
     */
    origin?: ContactOrigin;

    /**
     * @type {number}
     * @memberof FullContact
     */
    ownerId?: number;

    /**
     * @type {Array<PhoneNumber>}
     * @memberof FullContact
     */
    phoneNumbers?: Array<PhoneNumber>;

    /**
     * @type {string}
     * @memberof FullContact
     * @example en_US
     */
    preferredLocale?: string;

    /**
     * @type {string}
     * @memberof FullContact
     */
    preferredName?: string;

    /**
     * @type {string}
     * @memberof FullContact
     */
    prefix?: string;

    /**
     * @type {Array<Relationship>}
     * @memberof FullContact
     */
    relationships?: Array<Relationship>;

    /**
     * @type {Array<SocialAccount>}
     * @memberof FullContact
     */
    socialAccounts?: Array<SocialAccount>;

    /**
     * @type {string}
     * @memberof FullContact
     */
    sourceType?: FullContactSourceTypeEnum;

    /**
     * @type {string}
     * @memberof FullContact
     */
    spouseName?: string;

    /**
     * @type {string}
     * @memberof FullContact
     */
    suffix?: string;

    /**
     * @type {Array<number>}
     * @memberof FullContact
     */
    tagIds?: Array<number>;

    /**
     * @type {string}
     * @memberof FullContact
     */
    timeZone?: string;

    /**
     * @type {string}
     * @memberof FullContact
     */
    website?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum FullContactEmailStatusEnum {
    UnengagedMarketable = 'UnengagedMarketable',
    SingleOptIn = 'SingleOptIn',
    DoubleOptin = 'DoubleOptin',
    Confirmed = 'Confirmed',
    UnengagedNonMarketable = 'UnengagedNonMarketable',
    NonMarketable = 'NonMarketable',
    Lockdown = 'Lockdown',
    Bounce = 'Bounce',
    HardBounce = 'HardBounce',
    Manual = 'Manual',
    Admin = 'Admin',
    System = 'System',
    ListUnsubscribe = 'ListUnsubscribe',
    Feedback = 'Feedback',
    Spam = 'Spam',
    Invalid = 'Invalid',
    Deactivated = 'Deactivated'
}
/**
 * @export
 * @enum {string}
 */
export enum FullContactSourceTypeEnum {
    APPOINTMENT = 'APPOINTMENT',
    FORMAPIHOSTED = 'FORMAPIHOSTED',
    FORMAPIINTERNAL = 'FORMAPIINTERNAL',
    WEBFORM = 'WEBFORM',
    INTERNALFORM = 'INTERNALFORM',
    LANDINGPAGE = 'LANDINGPAGE',
    IMPORT = 'IMPORT',
    MANUAL = 'MANUAL',
    API = 'API',
    OTHER = 'OTHER',
    UNKNOWN = 'UNKNOWN'
}

