/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InvoicePayment
 */
export interface InvoicePayment {

    /**
     * @type {number}
     * @memberof InvoicePayment
     */
    amount?: number;

    /**
     * @type {number}
     * @memberof InvoicePayment
     */
    id?: number;

    /**
     * @type {number}
     * @memberof InvoicePayment
     */
    invoiceId?: number;

    /**
     * @type {Date}
     * @memberof InvoicePayment
     */
    lastUpdated?: Date;

    /**
     * @type {string}
     * @memberof InvoicePayment
     */
    note?: string;

    /**
     * @type {Date}
     * @memberof InvoicePayment
     */
    payDate?: Date;

    /**
     * @type {string}
     * @memberof InvoicePayment
     */
    payStatus?: string;

    /**
     * @type {number}
     * @memberof InvoicePayment
     */
    paymentId?: number;

    /**
     * @type {number}
     * @memberof InvoicePayment
     */
    refundInvoicePaymentId?: number;

    /**
     * @type {boolean}
     * @memberof InvoicePayment
     */
    skipCommission?: boolean;
}
