/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { NoteUser } from './note-user';
 /**
 * 
 *
 * @export
 * @interface Note
 */
export interface Note {

    /**
     * @type {string}
     * @memberof Note
     */
    body?: string;

    /**
     * @type {number}
     * @memberof Note
     */
    contactId?: number;

    /**
     * @type {Date}
     * @memberof Note
     */
    dateCreated?: Date;

    /**
     * @type {number}
     * @memberof Note
     */
    id?: number;

    /**
     * @type {Date}
     * @memberof Note
     */
    lastUpdated?: Date;

    /**
     * @type {NoteUser}
     * @memberof Note
     */
    lastUpdatedBy?: NoteUser;

    /**
     * @type {string}
     * @memberof Note
     */
    title?: string;

    /**
     * @type {string}
     * @memberof Note
     */
    type?: NoteTypeEnum;

    /**
     * @type {number}
     * @memberof Note
     */
    userId?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum NoteTypeEnum {
    Appointment = 'Appointment',
    Call = 'Call',
    Email = 'Email',
    Fax = 'Fax',
    Letter = 'Letter',
    Other = 'Other'
}

