/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomFieldMetaData } from './custom-field-meta-data';
 /**
 * 
 *
 * @export
 * @interface ObjectModel
 */
export interface ObjectModel {

    /**
     * @type {Array<CustomFieldMetaData>}
     * @memberof ObjectModel
     */
    customFields?: Array<CustomFieldMetaData>;

    /**
     * These fields are not transmitted by default on this model, but can be requested by specifying them in a comma-separated list in the optional_properties query parameter.
     *
     * @type {Array<string>}
     * @memberof ObjectModel
     */
    optionalProperties?: Array<string>;
}
