/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OpportunityContact
 */
export interface OpportunityContact {

    /**
     * @type {string}
     * @memberof OpportunityContact
     */
    companyName?: string;

    /**
     * @type {string}
     * @memberof OpportunityContact
     */
    email?: string;

    /**
     * @type {string}
     * @memberof OpportunityContact
     */
    firstName?: string;

    /**
     * @type {number}
     * @memberof OpportunityContact
     * @example 0
     */
    id: number;

    /**
     * @type {string}
     * @memberof OpportunityContact
     */
    jobTitle?: string;

    /**
     * @type {string}
     * @memberof OpportunityContact
     */
    lastName?: string;

    /**
     * @type {string}
     * @memberof OpportunityContact
     */
    phoneNumber?: string;
}
