/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CustomFieldValue } from './custom-field-value';
import { OpportunityContact } from './opportunity-contact';
import { SimpleOpportunityStage } from './simple-opportunity-stage';
import { SimpleUser } from './simple-user';
 /**
 * 
 *
 * @export
 * @interface Opportunity
 */
export interface Opportunity {

    /**
     * @type {number}
     * @memberof Opportunity
     */
    affiliateId?: number;

    /**
     * @type {OpportunityContact}
     * @memberof Opportunity
     */
    contact: OpportunityContact;

    /**
     * @type {Array<CustomFieldValue>}
     * @memberof Opportunity
     */
    customFields?: Array<CustomFieldValue>;

    /**
     * @type {Date}
     * @memberof Opportunity
     */
    dateCreated?: Date;

    /**
     * @type {Date}
     * @memberof Opportunity
     */
    estimatedCloseDate?: Date;

    /**
     * @type {number}
     * @memberof Opportunity
     */
    id?: number;

    /**
     * @type {number}
     * @memberof Opportunity
     */
    includeInForecast?: number;

    /**
     * @type {Date}
     * @memberof Opportunity
     */
    lastUpdated?: Date;

    /**
     * @type {Date}
     * @memberof Opportunity
     */
    nextActionDate?: Date;

    /**
     * @type {string}
     * @memberof Opportunity
     */
    nextActionNotes?: string;

    /**
     * @type {string}
     * @memberof Opportunity
     */
    opportunityNotes?: string;

    /**
     * @type {string}
     * @memberof Opportunity
     */
    opportunityTitle: string;

    /**
     * @type {number}
     * @memberof Opportunity
     */
    projectedRevenueHigh?: number;

    /**
     * @type {number}
     * @memberof Opportunity
     */
    projectedRevenueLow?: number;

    /**
     * @type {SimpleOpportunityStage}
     * @memberof Opportunity
     */
    stage: SimpleOpportunityStage;

    /**
     * @type {SimpleUser}
     * @memberof Opportunity
     */
    user?: SimpleUser;
}
