/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { OrderItemTax } from './order-item-tax';
import { Product_ } from './product_';
 /**
 * 
 *
 * @export
 * @interface OrderItem
 */
export interface OrderItem {

    /**
     * @type {number}
     * @memberof OrderItem
     */
    billingCycle?: number;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    cost?: number;

    /**
     * @type {string}
     * @memberof OrderItem
     */
    description?: string;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    discount?: number;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    frequency?: number;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    id?: number;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    jobRecurringId?: number;

    /**
     * @type {string}
     * @memberof OrderItem
     */
    name?: string;

    /**
     * @type {string}
     * @memberof OrderItem
     */
    notes?: string;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    numberOfPayments?: number;

    /**
     * @type {Array<OrderItemTax>}
     * @memberof OrderItem
     */
    orderItemTaxes?: Array<OrderItemTax>;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    price?: number;

    /**
     * @type {Product_}
     * @memberof OrderItem
     */
    product?: Product_;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    quantity?: number;

    /**
     * @type {boolean}
     * @memberof OrderItem
     */
    recurringBilling?: boolean;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    recurringCyclesCompleted?: number;

    /**
     * @type {string}
     * @memberof OrderItem
     */
    recurringEndDate?: string;

    /**
     * @type {boolean}
     * @memberof OrderItem
     */
    recurringInactive?: boolean;

    /**
     * @type {string}
     * @memberof OrderItem
     */
    recurringNextBillDate?: string;

    /**
     * @type {string}
     * @memberof OrderItem
     */
    recurringStartDate?: string;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    specialAmount?: number;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    specialId?: number;

    /**
     * @type {number}
     * @memberof OrderItem
     */
    specialPctOrAmt?: number;

    /**
     * @type {string}
     * @memberof OrderItem
     */
    type?: string;
}
