/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PaymentGateway } from './payment-gateway';
 /**
 * 
 *
 * @export
 * @interface PaymentPlan
 */
export interface PaymentPlan {

    /**
     * @type {boolean}
     * @memberof PaymentPlan
     */
    autoCharge?: boolean;

    /**
     * @type {number}
     * @memberof PaymentPlan
     */
    creditCardId?: number;

    /**
     * @type {number}
     * @memberof PaymentPlan
     */
    daysBetweenPayments: number;

    /**
     * @type {number}
     * @memberof PaymentPlan
     */
    initialPaymentAmount?: number;

    /**
     * @type {string}
     * @memberof PaymentPlan
     */
    initialPaymentDate?: string;

    /**
     * @type {number}
     * @memberof PaymentPlan
     */
    numberOfPayments: number;

    /**
     * @type {PaymentGateway}
     * @memberof PaymentPlan
     */
    paymentGateway?: PaymentGateway;

    /**
     * @type {string}
     * @memberof PaymentPlan
     */
    planStartDate: string;
}
