/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductOptionValue } from './product-option-value';
 /**
 * 
 *
 * @export
 * @interface ProductOption
 */
export interface ProductOption {

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    allowSpaces?: boolean;

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    canContainCharacter?: boolean;

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    canContainNumber?: boolean;

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    canEndWithCharacter?: boolean;

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    canEndWithNumber?: boolean;

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    canStartWithCharacter?: boolean;

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    canStartWithNumber?: boolean;

    /**
     * @type {number}
     * @memberof ProductOption
     */
    displayIndex?: number;

    /**
     * @type {number}
     * @memberof ProductOption
     */
    id?: number;

    /**
     * @type {string}
     * @memberof ProductOption
     */
    label?: string;

    /**
     * @type {number}
     * @memberof ProductOption
     */
    maxChars?: number;

    /**
     * @type {number}
     * @memberof ProductOption
     */
    minChars?: number;

    /**
     * @type {string}
     * @memberof ProductOption
     */
    name?: string;

    /**
     * @type {boolean}
     * @memberof ProductOption
     */
    required?: boolean;

    /**
     * @type {string}
     * @memberof ProductOption
     */
    textMessage?: string;

    /**
     * @type {string}
     * @memberof ProductOption
     */
    type?: ProductOptionTypeEnum;

    /**
     * @type {Array<ProductOptionValue>}
     * @memberof ProductOption
     */
    values?: Array<ProductOptionValue>;
}

/**
 * @export
 * @enum {string}
 */
export enum ProductOptionTypeEnum {
    FixedList = 'FixedList',
    Variable = 'Variable'
}

