/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductOption } from './product-option';
import { SubscriptionPlan_ } from './subscription-plan_';
 /**
 * 
 *
 * @export
 * @interface Product_
 */
export interface Product_ {

    /**
     * @type {number}
     * @memberof Product_
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Product_
     */
    productDesc?: string;

    /**
     * @type {string}
     * @memberof Product_
     */
    productName?: string;

    /**
     * @type {Array<ProductOption>}
     * @memberof Product_
     */
    productOptions?: Array<ProductOption>;

    /**
     * @type {number}
     * @memberof Product_
     */
    productPrice?: number;

    /**
     * @type {string}
     * @memberof Product_
     */
    productShortDesc?: string;

    /**
     * @type {string}
     * @memberof Product_
     */
    sku?: string;

    /**
     * @type {number}
     * @memberof Product_
     */
    status?: number;

    /**
     * @type {boolean}
     * @memberof Product_
     */
    subscriptionOnly?: boolean;

    /**
     * @type {Array<SubscriptionPlan_>}
     * @memberof Product_
     */
    subscriptionPlans?: Array<SubscriptionPlan_>;

    /**
     * @type {string}
     * @memberof Product_
     */
    url?: string;
}
