/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ProductOptionValue
 */
export interface ProductOptionValue {

    /**
     * @type {number}
     * @memberof ProductOptionValue
     */
    id?: number;

    /**
     * @type {number}
     * @memberof ProductOptionValue
     */
    index?: number;

    /**
     * @type {boolean}
     * @memberof ProductOptionValue
     */
    isDefault?: boolean;

    /**
     * @type {string}
     * @memberof ProductOptionValue
     */
    label?: string;

    /**
     * @type {number}
     * @memberof ProductOptionValue
     */
    priceAdjustment?: number;

    /**
     * @type {string}
     * @memberof ProductOptionValue
     */
    sku?: string;
}
