/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProductStatus } from './product-status';
 /**
 * 
 *
 * @export
 * @interface ProductStatusList
 */
export interface ProductStatusList {

    /**
     * @type {number}
     * @memberof ProductStatusList
     */
    count?: number;

    /**
     * @type {string}
     * @memberof ProductStatusList
     */
    next?: string;

    /**
     * @type {string}
     * @memberof ProductStatusList
     */
    previous?: string;

    /**
     * @type {Array<ProductStatus>}
     * @memberof ProductStatusList
     */
    productStatuses?: Array<ProductStatus>;

    /**
     * @type {string}
     * @memberof ProductStatusList
     */
    syncToken?: string;
}
