/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RequestNote
 */
export interface RequestNote {

    /**
     * @type {string}
     * @memberof RequestNote
     */
    body?: string;

    /**
     * @type {number}
     * @memberof RequestNote
     */
    contactId: number;

    /**
     * @type {string}
     * @memberof RequestNote
     */
    title?: string;

    /**
     * @type {string}
     * @memberof RequestNote
     */
    type?: RequestNoteTypeEnum;

    /**
     * @type {number}
     * @memberof RequestNote
     */
    userId?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum RequestNoteTypeEnum {
    Appointment = 'Appointment',
    Call = 'Call',
    Email = 'Email',
    Fax = 'Fax',
    Letter = 'Letter',
    Other = 'Other'
}

