/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RestHook
 */
export interface RestHook {

    /**
     * @type {string}
     * @memberof RestHook
     */
    eventKey?: string;

    /**
     * @type {string}
     * @memberof RestHook
     */
    hookUrl?: string;

    /**
     * @type {string}
     * @memberof RestHook
     */
    key?: string;

    /**
     * @type {string}
     * @memberof RestHook
     */
    status?: RestHookStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum RestHookStatusEnum {
    Unverified = 'Unverified',
    Verified = 'Verified',
    Inactive = 'Inactive'
}

