/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RestApplicationConfigurationModuleApplicationCompany } from './rest-application-configuration-module-application-company';
import { RestApplicationConfigurationModuleApplicationFeaturesEnabled } from './rest-application-configuration-module-application-features-enabled';
 /**
 * 
 *
 * @export
 * @interface RestApplicationConfigurationModuleApplication
 */
export interface RestApplicationConfigurationModuleApplication {

    /**
     * @type {RestApplicationConfigurationModuleApplicationCompany}
     * @memberof RestApplicationConfigurationModuleApplication
     */
    company?: RestApplicationConfigurationModuleApplicationCompany;

    /**
     * @type {string}
     * @memberof RestApplicationConfigurationModuleApplication
     */
    defaultViewLocale?: string;

    /**
     * @type {RestApplicationConfigurationModuleApplicationFeaturesEnabled}
     * @memberof RestApplicationConfigurationModuleApplication
     */
    featuresEnabled?: RestApplicationConfigurationModuleApplicationFeaturesEnabled;

    /**
     * @type {string}
     * @memberof RestApplicationConfigurationModuleApplication
     */
    timeZone?: string;
}
