/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RestApplicationConfigurationModuleAffiliate } from './rest-application-configuration-module-affiliate';
import { RestApplicationConfigurationModuleApplication } from './rest-application-configuration-module-application';
import { RestApplicationConfigurationModuleAppointment } from './rest-application-configuration-module-appointment';
import { RestApplicationConfigurationModuleContact } from './rest-application-configuration-module-contact';
import { RestApplicationConfigurationModuleECommerce } from './rest-application-configuration-module-ecommerce';
import { RestApplicationConfigurationModuleEMail } from './rest-application-configuration-module-email';
import { RestApplicationConfigurationModuleForms } from './rest-application-configuration-module-forms';
import { RestApplicationConfigurationModuleFulfillment } from './rest-application-configuration-module-fulfillment';
import { RestApplicationConfigurationModuleInvoice } from './rest-application-configuration-module-invoice';
import { RestApplicationConfigurationModuleNote } from './rest-application-configuration-module-note';
import { RestApplicationConfigurationModuleOpportunity } from './rest-application-configuration-module-opportunity';
import { RestApplicationConfigurationModuleTask } from './rest-application-configuration-module-task';
import { RestApplicationConfigurationModuleTemplate } from './rest-application-configuration-module-template';
 /**
 * 
 *
 * @export
 * @interface RestApplicationConfiguration
 */
export interface RestApplicationConfiguration {

    /**
     * @type {RestApplicationConfigurationModuleAffiliate}
     * @memberof RestApplicationConfiguration
     */
    affiliate?: RestApplicationConfigurationModuleAffiliate;

    /**
     * @type {RestApplicationConfigurationModuleApplication}
     * @memberof RestApplicationConfiguration
     */
    application?: RestApplicationConfigurationModuleApplication;

    /**
     * @type {RestApplicationConfigurationModuleAppointment}
     * @memberof RestApplicationConfiguration
     */
    appointment?: RestApplicationConfigurationModuleAppointment;

    /**
     * @type {RestApplicationConfigurationModuleContact}
     * @memberof RestApplicationConfiguration
     */
    contact?: RestApplicationConfigurationModuleContact;

    /**
     * @type {RestApplicationConfigurationModuleECommerce}
     * @memberof RestApplicationConfiguration
     */
    ecommerce?: RestApplicationConfigurationModuleECommerce;

    /**
     * @type {RestApplicationConfigurationModuleEMail}
     * @memberof RestApplicationConfiguration
     */
    email?: RestApplicationConfigurationModuleEMail;

    /**
     * @type {RestApplicationConfigurationModuleForms}
     * @memberof RestApplicationConfiguration
     */
    forms?: RestApplicationConfigurationModuleForms;

    /**
     * @type {RestApplicationConfigurationModuleFulfillment}
     * @memberof RestApplicationConfiguration
     */
    fulfillment?: RestApplicationConfigurationModuleFulfillment;

    /**
     * @type {RestApplicationConfigurationModuleInvoice}
     * @memberof RestApplicationConfiguration
     */
    invoice?: RestApplicationConfigurationModuleInvoice;

    /**
     * @type {RestApplicationConfigurationModuleNote}
     * @memberof RestApplicationConfiguration
     */
    note?: RestApplicationConfigurationModuleNote;

    /**
     * @type {RestApplicationConfigurationModuleOpportunity}
     * @memberof RestApplicationConfiguration
     */
    opportunity?: RestApplicationConfigurationModuleOpportunity;

    /**
     * @type {RestApplicationConfigurationModuleTask}
     * @memberof RestApplicationConfiguration
     */
    task?: RestApplicationConfigurationModuleTask;

    /**
     * @type {RestApplicationConfigurationModuleTemplate}
     * @memberof RestApplicationConfiguration
     */
    template?: RestApplicationConfigurationModuleTemplate;
}
