/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SalesPipeline
 */
export interface SalesPipeline {

    /**
     * @type {boolean}
     * @memberof SalesPipeline
     */
    endStage?: boolean;

    /**
     * @type {boolean}
     * @memberof SalesPipeline
     */
    isDefault?: boolean;

    /**
     * @type {number}
     * @memberof SalesPipeline
     */
    stageCount?: number;

    /**
     * @type {number}
     * @memberof SalesPipeline
     */
    stageId?: number;

    /**
     * @type {string}
     * @memberof SalesPipeline
     */
    stageName?: string;

    /**
     * @type {number}
     * @memberof SalesPipeline
     */
    stageOrder?: number;
}
