/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SocialAccount
 */
export interface SocialAccount {

    /**
     * @type {string}
     * @memberof SocialAccount
     */
    name?: string;

    /**
     * @type {string}
     * @memberof SocialAccount
     */
    type?: SocialAccountTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SocialAccountTypeEnum {
    Facebook = 'Facebook',
    Twitter = 'Twitter',
    LinkedIn = 'LinkedIn',
    Instagram = 'Instagram',
    Snapchat = 'Snapchat',
    YouTube = 'YouTube',
    Pinterest = 'Pinterest'
}

