/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface StackTraceElement
 */
export interface StackTraceElement {

    /**
     * @type {string}
     * @memberof StackTraceElement
     */
    classLoaderName?: string;

    /**
     * @type {string}
     * @memberof StackTraceElement
     */
    className?: string;

    /**
     * @type {string}
     * @memberof StackTraceElement
     */
    fileName?: string;

    /**
     * @type {number}
     * @memberof StackTraceElement
     */
    lineNumber?: number;

    /**
     * @type {string}
     * @memberof StackTraceElement
     */
    methodName?: string;

    /**
     * @type {string}
     * @memberof StackTraceElement
     */
    moduleName?: string;

    /**
     * @type {string}
     * @memberof StackTraceElement
     */
    moduleVersion?: string;

    /**
     * @type {boolean}
     * @memberof StackTraceElement
     */
    nativeMethod?: boolean;
}
