/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Subscription } from './subscription';
 /**
 * 
 *
 * @export
 * @interface SubscriptionList
 */
export interface SubscriptionList {

    /**
     * @type {number}
     * @memberof SubscriptionList
     */
    count?: number;

    /**
     * @type {string}
     * @memberof SubscriptionList
     */
    next?: string;

    /**
     * @type {string}
     * @memberof SubscriptionList
     */
    previous?: string;

    /**
     * @type {Array<Subscription>}
     * @memberof SubscriptionList
     */
    subscriptions?: Array<Subscription>;
}
