/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Tag } from './tag';
 /**
 * 
 *
 * @export
 * @interface Tags
 */
export interface Tags {

    /**
     * @type {number}
     * @memberof Tags
     */
    count?: number;

    /**
     * @type {string}
     * @memberof Tags
     */
    next?: string;

    /**
     * @type {string}
     * @memberof Tags
     */
    previous?: string;

    /**
     * @type {Array<Tag>}
     * @memberof Tags
     */
    tags?: Array<Tag>;
}
