/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BasicContact } from './basic-contact';
 /**
 * 
 *
 * @export
 * @interface Task
 */
export interface Task {

    /**
     * @type {boolean}
     * @memberof Task
     */
    completed?: boolean;

    /**
     * @type {Date}
     * @memberof Task
     */
    completionDate?: Date;

    /**
     * @type {BasicContact}
     * @memberof Task
     */
    contact?: BasicContact;

    /**
     * @type {Date}
     * @memberof Task
     */
    creationDate?: Date;

    /**
     * @type {string}
     * @memberof Task
     */
    description?: string;

    /**
     * @type {Date}
     * @memberof Task
     */
    dueDate?: Date;

    /**
     * @type {number}
     * @memberof Task
     */
    funnelId?: number;

    /**
     * @type {number}
     * @memberof Task
     */
    jgraphId?: number;

    /**
     * @type {Date}
     * @memberof Task
     */
    modificationDate?: Date;

    /**
     * @type {number}
     * @memberof Task
     */
    priority?: number;

    /**
     * Value in minutes before start_date to show pop-up reminder.   Acceptable values are in [`5`,`10`,`15`,`30`,`60`,`120`,`240`,`480`,`1440`,`2880`]
     *
     * @type {number}
     * @memberof Task
     */
    remindTime?: number;

    /**
     * @type {string}
     * @memberof Task
     */
    title?: string;

    /**
     * @type {string}
     * @memberof Task
     */
    type?: string;

    /**
     * @type {string}
     * @memberof Task
     */
    url?: string;

    /**
     * @type {number}
     * @memberof Task
     */
    userId?: number;
}
