/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContactAddress } from './contact-address';
import { CreateContactOrigin } from './create-contact-origin';
import {CreateOrPatchContact, CreateOrPatchContactSourceTypeEnum} from './create-or-patch-contact'
import { CustomFieldValue } from './custom-field-value';
import { EmailAddress } from './email-address';
import { FaxNumber } from './fax-number';
import { PhoneNumber } from './phone-number';
import { RequestCompanyReference } from './request-company-reference';
import { SocialAccount } from './social-account';
 /**
 *
 *
 * @export
 * @interface UpsertContact
 */
export interface UpsertContact extends CreateOrPatchContact {

    /**
     * @type {Array<ContactAddress>}
     * @memberof UpsertContact
     */
    addresses?: Array<ContactAddress>;

    /**
     * @type {Date}
     * @memberof UpsertContact
     */
    anniversary?: Date;

    /**
     * @type {Date}
     * @memberof UpsertContact
     */
    birthday?: Date;

    /**
     * @type {RequestCompanyReference}
     * @memberof UpsertContact
     */
    company?: RequestCompanyReference;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    contactType?: string;

    /**
     * @type {Array<CustomFieldValue>}
     * @memberof UpsertContact
     */
    customFields?: Array<CustomFieldValue>;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    duplicateOption?: UpsertContactDuplicateOptionEnum;

    /**
     * @type {Array<EmailAddress>}
     * @memberof UpsertContact
     */
    emailAddresses?: Array<EmailAddress>;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    familyName?: string;

    /**
     * @type {Array<FaxNumber>}
     * @memberof UpsertContact
     */
    faxNumbers?: Array<FaxNumber>;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    givenName?: string;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    jobTitle?: string;

    /**
     * @type {number}
     * @memberof UpsertContact
     */
    leadSourceId?: number;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    middleName?: string;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    optInReason?: string;

    /**
     * @type {CreateContactOrigin}
     * @memberof UpsertContact
     */
    origin?: CreateContactOrigin;

    /**
     * @type {number}
     * @memberof UpsertContact
     */
    ownerId?: number;

    /**
     * @type {Array<PhoneNumber>}
     * @memberof UpsertContact
     */
    phoneNumbers?: Array<PhoneNumber>;

    /**
     * @type {string}
     * @memberof UpsertContact
     * @example en_US
     */
    preferredLocale?: string;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    preferredName?: string;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    prefix?: string;

    /**
     * @type {Array<SocialAccount>}
     * @memberof UpsertContact
     */
    socialAccounts?: Array<SocialAccount>;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    sourceType?: CreateOrPatchContactSourceTypeEnum;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    spouseName?: string;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    suffix?: string;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    timeZone?: string;

    /**
     * @type {string}
     * @memberof UpsertContact
     */
    website?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum UpsertContactDuplicateOptionEnum {
    Email = 'Email',
    EmailAndName = 'EmailAndName'
}


