/* tslint:disable */
/* eslint-disable */
/**
 * Keap REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.655384-hf-202403291416
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RestUser } from './rest-user';
 /**
 * 
 *
 * @export
 * @interface Users
 */
export interface Users {

    /**
     * @type {number}
     * @memberof Users
     */
    count?: number;

    /**
     * @type {string}
     * @memberof Users
     */
    next?: string;

    /**
     * @type {string}
     * @memberof Users
     */
    previous?: string;

    /**
     * @type {Array<RestUser>}
     * @memberof Users
     */
    users?: Array<RestUser>;
}
